backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "blogs"
    label: "Blogs"
    folder: "content/blogs"
    create: true
    slug: '{{fields.title}}'
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown"}
      - { label: "Category", name: "category", widget: "string"}
      - { label: "Tags", name: "tags", widget: "list" }